version: "3"
services:
  backend:
    build:
      context: ./crud-movies-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./crud-movies-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
